import { getServiceClient } from '../../../lib/auth';

type Row = Record<string, any>;
export default async function SuperuserHealthPage() {
  const db = getServiceClient();
  const { data: health } = await db.from('superuser_business_health').select('*').single();
  const { data: kpis } = await db.from('superuser_kpis').select('*').single();
  const { data: subs } = await db.from('subscriptions').select('plan, monthly_value, status').eq('status', 'active');
  const { data: progress } = await db.from('prototype_progress').select('milestone, target_date, actual_date, status, notes').order('created_at');
  const h: Row = health || {}, k: Row = kpis || {}, subscriptionRows: Row[] = subs || [], progressRows: Row[] = progress || [];
  const mrr = Number(h.total_mrr || 0), arr = Number(h.total_arr || 0), ai = Number(h.ai_cost_last_30d || 0), infra = Number(h.infra_cost_last_30d || 0), direct = ai + infra, profit = mrr - direct;
  const plans: Record<string, number> = {}; subscriptionRows.forEach((s: Row) => { plans[s.plan] = (plans[s.plan] || 0) + 1; });
  const conversion = Number(k.active_subscriptions || 0) / Math.max(1, Number(k.active_accounts || 1));
  return <div className="space-y-8"><div><p className="text-sm font-medium text-blue-700">Superuser</p><h1 className="mt-1 text-3xl font-semibold text-gray-900">Business health & real-time KPIs</h1><p className="mt-2 text-sm text-gray-600">Revenue, direct cost, margin, adoption, value, and progress.</p></div><section className="grid gap-4 sm:grid-cols-4">{[['MRR',mrr],['ARR',arr],['Direct costs (30d)',direct],['Gross profit (30d)',profit]].map(([label,value]: [string, number]) => <div key={label} className="rounded-lg border border-gray-200 bg-white p-5"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-2xl font-semibold">${Number(value).toLocaleString()}</p></div>)}</section><section className="grid gap-4 sm:grid-cols-4">{[['Active accounts',k.active_accounts || 0],['Bids (30d)',k.bids_last_30d || 0],['Time saved (30d)',`${k.time_saved_minutes_last_30d || 0} min`],['Errors prevented (30d)',k.errors_prevented_last_30d || 0]].map(([label,value]: [string, any]) => <div key={label} className="rounded-lg border border-gray-200 bg-white p-5"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</section><section className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg border border-gray-200 bg-white p-5"><p className="text-sm text-gray-500">AI cost (30d)</p><p className="mt-2 text-xl font-semibold">${ai.toLocaleString()}</p></div><div className="rounded-lg border border-gray-200 bg-white p-5"><p className="text-sm text-gray-500">Infra cost (30d)</p><p className="mt-2 text-xl font-semibold">${infra.toLocaleString()}</p></div><div className="rounded-lg border border-gray-200 bg-white p-5"><p className="text-sm text-gray-500">Conversion rate</p><p className="mt-2 text-xl font-semibold">{(conversion * 100).toFixed(1)}%</p></div></section><section className="rounded-lg border border-gray-200 bg-white p-5"><h2>Prototype progress</h2>{progressRows.map((p: Row) => <p key={p.milestone} className="py-1"><span className="font-medium">{p.status}</span> — {p.milestone}</p>)}</section></div>;
}
