import { getServiceClient } from '../../../../lib/auth';
import { formatCurrency, formatDate, formatNumber } from '../../../../lib/admin-data';

export default async function TokenUsagePage() {
  const supabase = getServiceClient();
  const { data, error } = await supabase.from('ai_run_usage').select('id, ai_run_id, model, input_tokens, output_tokens, total_cost, created_at').order('created_at', { ascending: false }).limit(250);
  const totals = (data || []).reduce((acc, row) => ({ input: acc.input + Number(row.input_tokens || 0), output: acc.output + Number(row.output_tokens || 0), cost: acc.cost + Number(row.total_cost || 0) }), { input: 0, output: 0, cost: 0 });
  return <div className="space-y-6"><div><p className="text-sm font-medium text-blue-700">AI operations</p><h1 className="mt-1 text-3xl font-semibold text-gray-900">Token usage</h1><p className="mt-2 text-sm text-gray-600">Live usage telemetry from <code>ai_run_usage</code>.</p></div><section className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg border border-gray-200 bg-white p-5"><p className="text-sm text-gray-500">Input tokens</p><p className="mt-2 text-2xl font-semibold">{formatNumber(totals.input)}</p></div><div className="rounded-lg border border-gray-200 bg-white p-5"><p className="text-sm text-gray-500">Output tokens</p><p className="mt-2 text-2xl font-semibold">{formatNumber(totals.output)}</p></div><div className="rounded-lg border border-gray-200 bg-white p-5"><p className="text-sm text-gray-500">Recorded cost</p><p className="mt-2 text-2xl font-semibold">{formatCurrency(totals.cost)}</p></div></section>{error ? <p className="rounded border border-red-200 bg-red-50 p-4 text-sm text-red-700">Unable to load usage: {error.message}</p> : <div className="overflow-x-auto rounded-lg border border-gray-200 bg-white"><table className="min-w-full divide-y divide-gray-200 text-sm"><thead className="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr><th className="px-5 py-3">Run</th><th className="px-5 py-3">Model</th><th className="px-5 py-3">Input</th><th className="px-5 py-3">Output</th><th className="px-5 py-3">Cost</th><th className="px-5 py-3">Recorded</th></tr></thead><tbody className="divide-y divide-gray-100">{(data || []).map((row) => <tr key={row.id}><td className="px-5 py-4 font-mono text-xs text-gray-600">{row.ai_run_id}</td><td className="px-5 py-4 text-gray-600">{row.model || '—'}</td><td className="px-5 py-4 text-gray-600">{formatNumber(Number(row.input_tokens || 0))}</td><td className="px-5 py-4 text-gray-600">{formatNumber(Number(row.output_tokens || 0))}</td><td className="px-5 py-4 text-gray-600">{formatCurrency(Number(row.total_cost || 0))}</td><td className="px-5 py-4 text-gray-600">{formatDate(row.created_at)}</td></tr>)}{!data?.length && <tr><td colSpan={6} className="px-5 py-10 text-center text-gray-500">No token usage records available.</td></tr>}</tbody></table></div>}</div>;
}
