import { getServiceClient } from '../../../../lib/auth';
import { formatCurrency, formatDate } from '../../../../lib/admin-data';

export default async function CostLedgerPage() {
  const supabase = getServiceClient();
  const { data, error } = await supabase.from('platform_cost_ledger').select('id, account_id, ai_run_id, amount, currency, type, created_at').order('created_at', { ascending: false }).limit(250);
  const total = (data || []).reduce((sum, row) => sum + Number(row.amount || 0), 0);
  return <div className="space-y-6"><div><p className="text-sm font-medium text-blue-700">Finance operations</p><h1 className="mt-1 text-3xl font-semibold text-gray-900">Platform cost ledger</h1><p className="mt-2 text-sm text-gray-600">Live cost entries from <code>platform_cost_ledger</code>.</p></div><div className="rounded-lg border border-gray-200 bg-white p-5"><p className="text-sm text-gray-500">Recorded ledger total</p><p className="mt-2 text-2xl font-semibold">{formatCurrency(total)}</p></div>{error ? <p className="rounded border border-red-200 bg-red-50 p-4 text-sm text-red-700">Unable to load ledger: {error.message}</p> : <div className="overflow-x-auto rounded-lg border border-gray-200 bg-white"><table className="min-w-full divide-y divide-gray-200 text-sm"><thead className="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr><th className="px-5 py-3">Entry</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Currency</th><th className="px-5 py-3">AI run</th><th className="px-5 py-3">Recorded</th></tr></thead><tbody className="divide-y divide-gray-100">{(data || []).map((row) => <tr key={row.id}><td className="px-5 py-4 font-mono text-xs text-gray-600">{row.id}</td><td className="px-5 py-4 text-gray-600">{row.type || '—'}</td><td className="px-5 py-4 text-gray-600">{formatCurrency(Number(row.amount || 0))}</td><td className="px-5 py-4 text-gray-600">{row.currency || 'USD'}</td><td className="px-5 py-4 font-mono text-xs text-gray-600">{row.ai_run_id || '—'}</td><td className="px-5 py-4 text-gray-600">{formatDate(row.created_at)}</td></tr>)}{!data?.length && <tr><td colSpan={6} className="px-5 py-10 text-center text-gray-500">No cost ledger records available.</td></tr>}</tbody></table></div>}</div>;
}
