import Link from "next/link";
import { getCorporateContent } from "@/lib/site-content";

const defaultPillars = [
  ["READ THE TENDER", "Turn dense procurement documents into structured requirements, deadlines, evidence, conflicts, and the questions that matter."],
  ["PROVE THE FIT", "Match tender requirements against real products and inventory while preserving the evidence behind every result."],
  ["MAKE THE DECISION", "See scoring, gaps, risk, economics, and clarification needs in one auditable bid workspace."]
];

const css = `
:root{--navy:#071a33;--blue:#0b63ce;--teal:#00a6a6;--paper:#f6f9fc;--ink:#10233b;--muted:#64788f;--line:#d9e3ed}
*{box-sizing:border-box}html{scroll-behavior:smooth}html,body{margin:0;padding:0}body{background:var(--paper);color:var(--ink);font-family:Arial,Helvetica,sans-serif}.corporate-site{min-height:100vh;overflow:hidden}.site-container{width:min(1180px,calc(100% - 48px));margin:auto}a{text-decoration:none;color:inherit}
.site-header{height:78px;background:#fff;border-bottom:1px solid var(--line)}.nav-inner{height:100%;display:flex;align-items:center;justify-content:space-between}.wordmark{font-size:26px;font-weight:800;letter-spacing:-1.7px;color:var(--navy)}.wordmark span{color:var(--blue)}.wordmark b{color:var(--teal)}.desktop-nav{display:flex;gap:34px;margin-left:auto;margin-right:50px;font-size:14px;font-weight:700;color:#40566d}.desktop-nav a:hover{color:var(--blue)}.nav-actions{display:flex;align-items:center;gap:22px;font-size:14px;font-weight:700}.text-link{color:#40566d}.nav-cta,.primary-button{display:inline-flex;align-items:center;gap:12px;background:var(--blue);color:#fff;padding:13px 19px;border-radius:5px;font-weight:700;box-shadow:0 8px 22px rgba(11,99,206,.18)}.nav-cta:hover,.primary-button:hover{background:#084f9f}
.hero-section{position:relative;color:#fff;background:linear-gradient(135deg,#06172d 0%,#092d5a 55%,#07536e 100%)}.hero-section:after{content:"";position:absolute;width:620px;height:620px;right:-190px;top:-160px;background:radial-gradient(circle,rgba(0,196,190,.28),transparent 65%);pointer-events:none}.hero-grid{min-height:650px;display:grid;grid-template-columns:1fr 1fr;gap:58px;align-items:center;padding:82px 0 94px}.hero-copy{position:relative;z-index:2}.eyebrow{margin-bottom:18px;font-size:11px;font-weight:800;letter-spacing:2px;color:var(--blue)}.hero-copy .eyebrow{color:#7ee4df}.eyebrow-dot{display:inline-block;width:7px;height:7px;margin-right:9px;border-radius:50%;background:var(--teal)}h1{font-size:clamp(50px,6vw,78px);line-height:.98;letter-spacing:-4px;margin:0 0 28px;max-width:680px}.hero-lede{max-width:610px;margin:0;color:#d7e6f5;font-size:19px;line-height:1.62}.hero-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:35px}.secondary-button{display:inline-flex;align-items:center;padding:13px 19px;border:1px solid rgba(255,255,255,.35);border-radius:5px;color:#fff;font-weight:700}.secondary-button:hover{background:rgba(255,255,255,.08)}.hero-note{margin-top:18px;color:#a8bdd1;font-size:12px}
.hero-visual{position:relative;z-index:2}.app-window{overflow:hidden;background:#fff;border:1px solid rgba(255,255,255,.35);border-radius:9px;box-shadow:0 35px 80px rgba(0,0,0,.36);transform:rotate(1deg)}.window-top{height:48px;display:flex;align-items:center;justify-content:space-between;padding:0 18px;background:#edf3f8;border-bottom:1px solid var(--line);color:#4c6278;font-size:11px;font-weight:700}.window-top b{padding:5px 8px;border-radius:12px;background:#e3eaf1;color:#62758a;font-size:8px;letter-spacing:1px}.window-body{display:flex;min-height:360px}.mini-sidebar{width:55px;background:#08254a;padding:14px 10px;display:flex;flex-direction:column;align-items:center;gap:18px}.mini-sidebar strong{width:30px;height:30px;display:grid;place-items:center;border-radius:6px;background:var(--blue);color:#fff}.mini-sidebar i{width:17px;height:17px;border:1px solid #7590ad;border-radius:4px;opacity:.7}.mini-main{flex:1;padding:25px;background:#fbfdff}.mini-breadcrumb{font-size:8px;letter-spacing:1.3px;color:#8194a8}.mini-title-row{display:flex;justify-content:space-between;gap:12px;margin:16px 0 20px}.mini-title-row strong{display:block;color:#132d49;font-size:18px}.mini-title-row small{display:block;margin-top:5px;color:#8091a2;font-size:9px}.decision-pill{white-space:nowrap;height:max-content;padding:7px 9px;border:1px solid #ffd49d;border-radius:12px;background:#fff2df;color:#b75a00;font-size:8px}.metric-row{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-bottom:12px}.metric-row div,.mini-card{background:#fff;border:1px solid #e0e7ee;border-radius:5px}.metric-row div{padding:12px}.metric-row small,.small-card small{display:block;color:#7d8fa1;font-size:8px;letter-spacing:.7px}.metric-row strong{display:block;margin-top:6px;color:#102a43;font-size:22px}.mini-card{padding:14px}.bar-title{display:flex;justify-content:space-between;color:#38516c;font-size:10px;font-weight:700}.progress{height:7px;margin:13px 0;background:#e6edf4;border-radius:5px}.progress span{display:block;width:42%;height:100%;background:linear-gradient(90deg,var(--blue),var(--teal));border-radius:5px}.mini-lines{display:grid;gap:7px}.mini-lines i{height:6px;background:#e8eef4;border-radius:4px}.mini-lines i:nth-child(1){width:92%}.mini-lines i:nth-child(2){width:74%}.mini-lines i:nth-child(3){width:84%}.mini-bottom{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.small-card strong{display:block;margin:6px 0;color:#132c48;font-size:17px}.small-card em{font-size:8px;color:#61738a;font-style:normal}
.trust-strip{background:#fff;border-bottom:1px solid var(--line)}.trust-inner{min-height:70px;display:flex;align-items:center;justify-content:space-between;gap:25px}.trust-inner>span{font-size:10px;font-weight:800;letter-spacing:1.6px;color:#6d8095}.trust-inner div{display:flex;align-items:center;gap:18px;color:#54708b;font-size:9px;font-weight:700;letter-spacing:1.2px}.trust-inner i{font-style:normal;color:var(--teal);font-size:15px}
.platform-section,.pricing-section{background:#fff}.platform-section{padding:108px 0 116px}.section-intro{max-width:770px}.section-intro h2,.vertical-section h2,.pricing-inner h2{margin:0;color:var(--navy);font-size:51px;line-height:1.04;letter-spacing:-2.5px}.section-intro h2 span,.vertical-section h2 span,.pricing-inner h2 span{color:var(--blue)}.section-intro p{max-width:670px;margin-top:23px;color:var(--muted);font-size:17px}.feature-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:56px}.feature-card{position:relative;min-height:275px;padding:28px;border:1px solid var(--line);border-radius:7px;background:#fff}.feature-number{color:var(--teal);font-size:11px;font-weight:800;letter-spacing:1.5px}.feature-card h3{margin:76px 0 13px;color:var(--navy);font-size:21px}.feature-card p{margin:0;max-width:300px;color:var(--muted);font-size:14px;line-height:1.65}.feature-arrow{position:absolute;top:25px;right:25px;color:var(--blue);font-size:21px}
.workflow-section{padding:108px 0;background:var(--navy);color:#fff}.workflow-grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:100px}.eyebrow.light{color:#79deda}.workflow-grid h2{margin:0;font-size:59px;line-height:.98;letter-spacing:-3px}.workflow-grid h2 strong{color:#62d8d3}.workflow-grid>div:first-child p{max-width:370px;margin-top:25px;color:#b5c8db}.workflow-list>div{display:grid;grid-template-columns:55px 1fr;column-gap:20px;padding:0 0 27px;margin-bottom:27px;border-bottom:1px solid rgba(255,255,255,.13)}.workflow-list>div:last-child{border-bottom:0}.workflow-list b{color:#67d8d2;font-size:11px;letter-spacing:1px}.workflow-list span{font-size:20px;font-weight:700}.workflow-list p{grid-column:2;margin:7px 0 0;color:#aebfd1;font-size:14px}
.vertical-section{padding:108px 0;background:#eef5fb}.vertical-grid{display:grid;grid-template-columns:1fr 1fr;gap:90px}.vertical-copy{padding-top:35px}.vertical-copy p{max-width:500px;color:#526b83;font-size:18px}.vertical-tags{display:flex;flex-wrap:wrap;gap:9px;margin-top:29px}.vertical-tags span{padding:10px 12px;border:1px solid #c9d8e7;border-radius:4px;background:#fff;color:var(--navy);font-size:10px;font-weight:800;letter-spacing:1px}.pricing-section{padding:108px 0}.pricing-inner{max-width:700px}.pricing-inner p{margin:20px 0 30px;color:var(--muted);font-size:17px}.site-footer{padding:43px 0 25px;background:#071a33;color:#b4c6d8}.footer-top{display:flex;justify-content:space-between;align-items:center;padding-bottom:30px;border-bottom:1px solid rgba(255,255,255,.12)}.footer-top .wordmark{color:#fff}.footer-top .wordmark span{color:#73c9ff}.footer-top .wordmark b{color:#58d3ce}.footer-links{display:flex;gap:25px;font-size:12px}.footer-bottom{display:flex;justify-content:space-between;padding-top:21px;color:#8198af;font-size:10px}
@media(max-width:850px){.site-container{width:calc(100% - 30px)}.desktop-nav{display:none}.nav-actions .text-link{display:none}.hero-grid,.workflow-grid,.vertical-grid{grid-template-columns:1fr}.hero-grid{padding:58px 0 70px}.hero-copy h1{font-size:52px;letter-spacing:-2.6px}.hero-visual{margin-top:18px}.feature-grid{grid-template-columns:1fr}.trust-inner{padding:18px 0;align-items:flex-start;flex-direction:column}.trust-inner div{flex-wrap:wrap;gap:9px}.section-intro h2,.vertical-section h2,.pricing-inner h2{font-size:40px}.workflow-grid{gap:55px}.workflow-grid h2{font-size:49px}.footer-top,.footer-bottom{align-items:flex-start;gap:25px;flex-direction:column}.footer-links{flex-wrap:wrap}}
`;

export default async function HomePage(){
  const content=await getCorporateContent();
  const hero=content.find(c=>c.key==="hero")?.value as any||{};
  const pillars=(content.find(c=>c.key==="pillars")?.value as any[])??defaultPillars;
  return <>
    <style dangerouslySetInnerHTML={{__html:css}}/>
    <main className="corporate-site">
      <header className="site-header"><div className="site-container nav-inner"><Link href="/" className="wordmark"><span>PIE</span><b>ify</b></Link><nav className="desktop-nav"><Link href="#platform">Platform</Link><Link href="#how-it-works">How it works</Link><Link href="#verticals">Industries</Link><Link href="#pricing">Pricing</Link></nav><div className="nav-actions"><Link href="/demo" className="text-link">Sign in</Link><Link href="/demo" className="nav-cta">See PIEify <span>→</span></Link></div></div></header>
      <section className="hero-section"><div className="site-container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot"/> PROCUREMENT INTELLIGENCE ENGINE</div><h1>{hero.title||"Turn the tender into a decision."}</h1><p className="hero-lede">{hero.body||"PIEify turns complex procurement documents, product capability, inventory, scoring, and economics into one evidence-backed bid decision."}</p><div className="hero-actions"><Link href="/demo" className="primary-button">Explore the platform <span>→</span></Link><Link href="#how-it-works" className="secondary-button">See how it works</Link></div><p className="hero-note">Built for teams that cannot afford to guess.</p></div>
        <div className="hero-visual"><div className="app-window"><div className="window-top"><span>PIEify / Bid workspace</span><b>ILLUSTRATIVE</b></div><div className="window-body"><aside className="mini-sidebar"><strong>P</strong><i/><i/><i/><i/><i/></aside><div className="mini-main"><small className="mini-breadcrumb">TENDERS / ACTIVE BID</small><div className="mini-title-row"><div><strong>Procurement decision</strong><small>Evidence-backed review</small></div><b className="decision-pill">BID WITH QUESTIONS</b></div><div className="metric-row"><div><small>Requirements</small><strong>—</strong></div><div><small>Matched</small><strong>—</strong></div><div><small>Questions</small><strong>—</strong></div></div><div className="mini-card"><div className="bar-title"><span>Requirement coverage</span><b>—</b></div><div className="progress"><span/></div><div className="mini-lines"><i/><i/><i/></div></div><div className="mini-bottom"><div className="mini-card small-card"><small>SCORING</small><strong>—</strong><em>Awaiting tender data</em></div><div className="mini-card small-card"><small>INVENTORY</small><strong>—</strong><em>Live data when connected</em></div></div></div></div></div></div>
      </div></section>
      <section className="trust-strip"><div className="site-container trust-inner"><span>ONE WORKSPACE. FROM TENDER TO OUTCOME.</span><div><b>DOCUMENT</b><i>→</i><b>REQUIREMENTS</b><i>→</i><b>MATCH</b><i>→</i><b>SCORE</b><i>→</i><b>DECIDE</b></div></div></section>
      <section id="platform" className="platform-section"><div className="site-container"><div className="section-intro"><div className="eyebrow">THE PLATFORM</div><h2>Stop hunting through documents.<br/><span>Start managing the decision.</span></h2><p>PIEify gives procurement teams a structured operating system for complex bids — without hiding the evidence underneath a pretty dashboard.</p></div><div className="feature-grid">{pillars.slice(0,3).map((p:any,i:number)=>{const [title,body]=p;return <article className="feature-card" key={title}><div className="feature-number">0{i+1}</div><h3>{title}</h3><p>{body}</p><span className="feature-arrow">↗</span></article>})}</div></div></section>
      <section id="how-it-works" className="workflow-section"><div className="site-container workflow-grid"><div><div className="eyebrow light">HOW IT WORKS</div><h2>From tender<br/><strong>to answer.</strong></h2><p>Every step stays connected. Every conclusion can be traced back to evidence.</p></div><div className="workflow-list"><div><b>01</b><span>Capture</span><p>Tender documents, addenda, requirements and submission rules.</p></div><div><b>02</b><span>Understand</span><p>Structure requirements and surface gaps, conflicts and questions.</p></div><div><b>03</b><span>Match &amp; score</span><p>Compare against real product and inventory evidence using the tender's rules.</p></div><div><b>04</b><span>Decide</span><p>BID, BID WITH QUESTIONS, custom-build path, or PASS — with the record to support it.</p></div></div></div></section>
      <section id="verticals" className="vertical-section"><div className="site-container vertical-grid"><div><div className="eyebrow">BUILT TO EXPAND</div><h2>One procurement engine.<br/><span>Multiple verticals.</span></h2></div><div className="vertical-copy"><p>PIEify starts where procurement is complex, specifications are unforgiving, and the cost of a bad assumption is high.</p><div className="vertical-tags"><span>FIRE APPARATUS</span><span>EMERGENCY VEHICLES</span><span>PUBLIC SAFETY</span><span>CAPITAL EQUIPMENT</span></div></div></div></section>
      <section id="pricing" className="pricing-section"><div className="site-container pricing-inner"><div className="eyebrow">PRICING</div><h2>Start with the work.<br/><span>Scale when you need to.</span></h2><p>Simple plans for procurement teams.</p><Link href="/demo" className="primary-button">Explore PIEify <span>→</span></Link></div></section>
      <footer className="site-footer"><div className="site-container footer-top"><Link href="/" className="wordmark"><span>PIE</span><b>ify</b></Link><div className="footer-links"><Link href="#platform">Platform</Link><Link href="#how-it-works">How it works</Link><Link href="#verticals">Industries</Link><Link href="#pricing">Pricing</Link><Link href="/demo">Sign in</Link></div></div><div className="site-container footer-bottom"><span>© {new Date().getFullYear()} PIEify. Procurement Intelligence Engine.</span><span>Evidence before assumptions.</span></div></footer>
    </main>
  </>;
}
