import Link from 'next/link';
import { getServiceClient } from '../../../../lib/auth';
export const dynamic='force-dynamic';
const names:Record<string,string>={organizations:'Organization',users:'User',subscriptions:'Subscription', 'demo-requests':'Demo request',tickets:'Support ticket',tenders:'Tender',requirements:'Requirement',inventory:'Inventory item',catalogs:'Catalog',relationships:'Business relationship',extraction:'Extraction',matching:'Match result',scoring:'Score run',questions:'Clarification question',ai:'AI run',automations:'Automation',workflows:'Workflow',integrations:'Integration run','data-quality':'Exception',revenue:'Subscription',usage:'Usage record',costs:'Cost record',deployments:'Deployment',security:'Security event',audit:'Audit event',settings:'Platform setting'};
export default async function RecordPage({params}:{params:Promise<{section:string;id:string}>}){
 const {section,id}=await params; const db=await getServiceClient(); const table=({organizations:'accounts',users:'profiles',subscriptions:'subscriptions','demo-requests':'demo_requests',tickets:'support_tickets',tenders:'bid_sessions',requirements:'requirements',inventory:'inventory_items',catalogs:'catalogs',relationships:'business_relationships',extraction:'document_workflows',matching:'match_results',scoring:'score_runs',questions:'clarification_questions',ai:'ai_runs',automations:'document_workflows',workflows:'document_workflows',integrations:'integration_sync_runs','data-quality':'exception_queue_items',revenue:'subscriptions',usage:'ai_run_usage',costs:'platform_cost_ledger',deployments:'deployment_events',security:'audit_events',audit:'audit_events',settings:'platform_settings'} as Record<string,string>)[section];
 if(!table) return <div className="hs-page-title">Not configured</div>;
 const {data,error}=await db.from(table).select('*').eq('id',id).maybeSingle();
 if(error) return <div><h1 className="hs-page-title">Not configured</h1><p className="hs-page-sub">{error.message}</p></div>;
 if(!data) return <div><Link href={`/app/superuser/${section}`} className="hs-breadcrumb">← {names[section]||'Records'}</Link><h1 className="hs-page-title">Record not found</h1><p className="hs-page-sub">No matching production record exists.</p></div>;
 const entries=Object.entries(data as Record<string,unknown>);
 return <div><div className="hs-breadcrumb"><Link href="/app/superuser">Platform Home</Link> / <Link href={`/app/superuser/${section}`}>{names[section]||section}</Link> / Record</div><div className="flex items-start justify-between gap-4"><div><h1 className="hs-page-title">{String((data as any).name || (data as any).subject || (data as any).email || names[section] || 'Record')}</h1><p className="hs-page-sub">{names[section]||section} · production record</p></div><Link href={`/app/superuser/${section}`} className="hs-btn">Back to {names[section]||'index'}</Link></div><div className="mt-5 grid gap-5 lg:grid-cols-[1.7fr_1fr]"><section className="rounded-lg border border-gray-200 bg-white"><div className="border-b border-gray-200 px-5 py-4"><h2 className="font-semibold">About this record</h2></div><dl className="grid grid-cols-1 md:grid-cols-2">{entries.map(([k,v])=><div key={k} className="border-b border-gray-100 px-5 py-4"><dt className="text-xs text-gray-500">{k.replace(/_/g,' ')}</dt><dd className="mt-1 break-words text-sm text-gray-900">{v===null||v===undefined||v===''?'—':typeof v==='object'?JSON.stringify(v):String(v)}</dd></div>)}</dl></section><aside className="rounded-lg border border-gray-200 bg-white h-fit"><div className="border-b border-gray-200 px-5 py-4"><h2 className="font-semibold">Record context</h2></div><div className="px-5 py-5 text-sm text-gray-600">This view is populated from the production record. Related objects are shown only when corresponding production relationships exist.</div></aside></div></div>;
}
