import Link from 'next/link';
import { getServiceClient } from '../../lib/auth';

export const dynamic = 'force-dynamic';

const n = (v: unknown) => Number(v || 0).toLocaleString();
const money = (v: unknown) => `$${Number(v || 0).toFixed(2)}`;
const dt = (v: unknown) => v ? new Date(String(v)).toLocaleString() : '—';

async function count(db: any, table: string) {
  const { count, error } = await db.from(table).select('*', { count: 'exact', head: true });
  return error ? null : count ?? 0;
}

export default async function SuperuserHome() {
  const db = getServiceClient();
  const [accounts, users, tenders, inventory, demoRequests, aiRuns, toolCalls, workflows, syncRuns, auditEvents, usage, cost, exceptions] = await Promise.all([
    count(db, 'accounts'), count(db, 'profiles'), count(db, 'bid_sessions'), count(db, 'inventory_items'), count(db, 'demo_requests'), count(db, 'ai_runs'), count(db, 'ai_tool_calls'), count(db, 'document_workflows'), count(db, 'integration_sync_runs'), count(db, 'audit_events'), count(db, 'ai_run_usage'), count(db, 'platform_cost_ledger'), count(db, 'exception_queue_items'),
  ]);
  const [usageRows, runRows, toolRows, demoRows, workflowRows, syncRows, auditRows, exceptionRows, costRows] = await Promise.all([
    db.from('ai_run_usage').select('provider,model,input_tokens,output_tokens,cached_input_tokens,actual_cost,estimated_cost,created_at').order('created_at', { ascending: false }).limit(12),
    db.from('ai_runs').select('id,account_id,bid_session_id,run_type,model,model_version,status,started_at,completed_at').order('started_at', { ascending: false }).limit(10),
    db.from('ai_tool_calls').select('ai_run_id,tool_name,status,latency_ms,created_at').order('created_at', { ascending: false }).limit(10),
    db.from('demo_requests').select('id,first_name,last_name,company,email,status,created_at').order('created_at', { ascending: false }).limit(8),
    db.from('document_workflows').select('id,name,status,current_step,updated_at').order('updated_at', { ascending: false }).limit(8),
    db.from('integration_sync_runs').select('id,direction,entity_type,status,started_at,records_read,records_written,records_failed').order('started_at', { ascending: false }).limit(8),
    db.from('audit_events').select('id,event_type,entity_type,action,occurred_at').order('occurred_at', { ascending: false }).limit(12),
    db.from('exception_queue_items').select('*').order('created_at', { ascending: false }).limit(8),
    db.from('platform_cost_ledger').select('cost_category,provider,model,quantity,unit,total_cost,currency,created_at').order('created_at', { ascending: false }).limit(12),
  ]);
  const usageData = usageRows.data || [];
  const inputTokens = usageData.reduce((a: number, r: any) => a + Number(r.input_tokens || 0), 0);
  const outputTokens = usageData.reduce((a: number, r: any) => a + Number(r.output_tokens || 0), 0);
  const cachedTokens = usageData.reduce((a: number, r: any) => a + Number(r.cached_input_tokens || 0), 0);
  const actualAiCost = usageData.reduce((a: number, r: any) => a + Number(r.actual_cost || r.estimated_cost || 0), 0);
  const recentCosts = (costRows.data || []).reduce((a: number, r: any) => a + Number(r.total_cost || 0), 0);
  const openDemos = (demoRows.data || []).filter((r: any) => !['closed','completed','converted'].includes(String(r.status || '').toLowerCase())).length;
  const failedAgents = (runRows.data || []).filter((r: any) => ['failed','error'].includes(String(r.status || '').toLowerCase()));
  const failedTools = (toolRows.data || []).filter((r: any) => ['failed','error'].includes(String(r.status || '').toLowerCase()));
  const failedSyncs = (syncRows.data || []).filter((r: any) => ['failed','error'].includes(String(r.status || '').toLowerCase()));
  const openExceptions = exceptionRows.data || [];
  return <div className="space-y-7">
    <div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-blue-700">PIEify Platform</p><h1 className="mt-1 text-3xl font-semibold text-gray-900">Good afternoon. Here is what is happening.</h1><p className="mt-2 text-sm text-gray-600">Platform control plane. Live operational data only.</p></div><div className="text-right text-xs text-gray-500">Friday, September 4, 2026<br/><span className="font-medium text-gray-700">Live production telemetry</span></div></div>
    <section className="grid gap-3 md:grid-cols-4 lg:grid-cols-7">{[['Organizations',accounts],['Users',users],['Tenders',tenders],['Inventory',inventory],['Demo requests',demoRequests],['AI runs',aiRuns],['Exceptions',exceptions]].map(([label,value]) => <div key={String(label)} className="rounded-lg border border-gray-200 bg-white p-4"><div className="text-xs text-gray-500">{label}</div><div className="mt-1 text-2xl font-semibold text-gray-900">{value === null ? '—' : n(value)}</div></div>)}</section>
    <section className="grid gap-5 lg:grid-cols-[1.6fr_1fr]">
      <div className="rounded-lg border border-gray-200 bg-white"><div className="flex items-center justify-between border-b border-gray-200 px-5 py-4"><div><h2 className="font-semibold text-gray-900">AI & agent activity</h2><p className="text-xs text-gray-500">What the platform's AI execution layer is actually doing.</p></div><Link className="text-xs font-semibold text-blue-700" href="/app/superuser/ai">View AI operations</Link></div><div className="grid grid-cols-3 border-b border-gray-200"><div className="p-5"><div className="text-xs text-gray-500">Input tokens (recent)</div><div className="mt-1 text-xl font-semibold">{n(inputTokens)}</div></div><div className="p-5"><div className="text-xs text-gray-500">Output tokens (recent)</div><div className="mt-1 text-xl font-semibold">{n(outputTokens)}</div></div><div className="p-5"><div className="text-xs text-gray-500">AI cost (recent)</div><div className="mt-1 text-xl font-semibold">{money(actualAiCost)}</div></div></div><div className="divide-y divide-gray-100">{(runRows.data || []).slice(0,6).map((r:any) => <div key={r.id} className="flex items-center justify-between px-5 py-3 text-sm"><div><span className="font-medium text-gray-900">{r.run_type || 'AI run'}</span><span className="ml-2 text-xs text-gray-500">{r.model || 'model unknown'}</span></div><div className="flex items-center gap-4"><span className="text-xs text-gray-500">{dt(r.started_at)}</span><span className={`rounded-full px-2 py-1 text-[11px] ${['failed','error'].includes(String(r.status).toLowerCase()) ? 'bg-red-50 text-red-700' : 'bg-gray-100 text-gray-700'}`}>{r.status || 'unknown'}</span></div></div>)}{!(runRows.data || []).length && <div className="px-5 py-6 text-sm text-gray-500">No AI runs recorded.</div>}</div></div>
      <div className="rounded-lg border border-gray-200 bg-white"><div className="border-b border-gray-200 px-5 py-4"><h2 className="font-semibold text-gray-900">Attention required</h2><p className="text-xs text-gray-500">Only surfaced from actual platform records.</p></div><div className="divide-y divide-gray-100"><div className="flex justify-between px-5 py-4"><span className="text-sm">AI runs failed</span><b className="text-red-700">{n(failedAgents.length)}</b></div><div className="flex justify-between px-5 py-4"><span className="text-sm">AI tool calls failed</span><b className="text-red-700">{n(failedTools.length)}</b></div><div className="flex justify-between px-5 py-4"><span className="text-sm">Sync runs failed</span><b className="text-red-700">{n(failedSyncs.length)}</b></div><div className="flex justify-between px-5 py-4"><span className="text-sm">Open exception records</span><b>{n(openExceptions.length)}</b></div><div className="flex justify-between px-5 py-4"><span className="text-sm">Outstanding demo requests</span><b>{n(openDemos)}</b></div></div></div>
    </section>
    <section className="grid gap-5 lg:grid-cols-2">
      <div className="rounded-lg border border-gray-200 bg-white"><div className="flex items-center justify-between border-b border-gray-200 px-5 py-4"><div><h2 className="font-semibold">Demo requests</h2><p className="text-xs text-gray-500">Real inbound demand from the corporate site.</p></div><Link href="/app/superuser/demo-requests" className="text-xs font-semibold text-blue-700">Open queue</Link></div><div className="divide-y divide-gray-100">{(demoRows.data || []).map((r:any)=><div key={r.id} className="flex items-center justify-between px-5 py-3"><div><div className="text-sm font-medium">{[r.first_name,r.last_name].filter(Boolean).join(' ') || 'Unnamed request'}</div><div className="text-xs text-gray-500">{r.company || 'Company not supplied'} · {r.email || 'Email not supplied'}</div></div><div className="text-right"><div className="text-xs font-medium">{r.status || 'status unknown'}</div><div className="text-[11px] text-gray-500">{dt(r.created_at)}</div></div></div>)}{!(demoRows.data || []).length && <div className="px-5 py-6 text-sm text-gray-500">No demo requests recorded.</div>}</div></div>
      <div className="rounded-lg border border-gray-200 bg-white"><div className="flex items-center justify-between border-b border-gray-200 px-5 py-4"><div><h2 className="font-semibold">Automations & workflows</h2><p className="text-xs text-gray-500">Workflow and integration execution.</p></div><Link href="/app/superuser/automations" className="text-xs font-semibold text-blue-700">Open operations</Link></div><div className="divide-y divide-gray-100">{(workflowRows.data || []).map((r:any)=><div key={r.id} className="flex items-center justify-between px-5 py-3"><div><div className="text-sm font-medium">{r.name || 'Unnamed workflow'}</div><div className="text-xs text-gray-500">Step {r.current_step ?? '—'} · updated {dt(r.updated_at)}</div></div><span className="rounded-full bg-gray-100 px-2 py-1 text-[11px]">{r.status || 'unknown'}</span></div>)}{!(workflowRows.data || []).length && <div className="px-5 py-6 text-sm text-gray-500">No document workflows recorded.</div>}</div></div>
    </section>
    <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-lg border border-gray-200 bg-white"><div className="border-b border-gray-200 px-5 py-4"><h2 className="font-semibold">Integration runs</h2><p className="text-xs text-gray-500">Inbound/outbound synchronization and failures.</p></div><div className="divide-y divide-gray-100">{(syncRows.data || []).map((r:any)=><div key={r.id} className="grid grid-cols-[1fr_auto] gap-3 px-5 py-3 text-sm"><div><div className="font-medium">{r.entity_type || 'Unknown entity'} · {r.direction || 'unknown direction'}</div><div className="text-xs text-gray-500">Read {r.records_read ?? 0} · wrote {r.records_written ?? 0} · failed {r.records_failed ?? 0}</div></div><span className="text-xs text-gray-500">{r.status || 'unknown'}</span></div>)}{!(syncRows.data || []).length && <div className="px-5 py-6 text-sm text-gray-500">No integration sync runs recorded.</div>}</div></div><div className="rounded-lg border border-gray-200 bg-white"><div className="border-b border-gray-200 px-5 py-4"><h2 className="font-semibold">Platform economics & usage</h2><p className="text-xs text-gray-500">Observed ledger and AI usage records.</p></div><div className="grid grid-cols-2 divide-x divide-gray-200"><div className="p-5"><div className="text-xs text-gray-500">Usage rows</div><div className="mt-1 text-xl font-semibold">{usage === null ? '—' : n(usage)}</div></div><div className="p-5"><div className="text-xs text-gray-500">Cost ledger rows</div><div className="mt-1 text-xl font-semibold">{cost === null ? '—' : n(cost)}</div></div></div><div className="border-t border-gray-200 px-5 py-4 text-sm"><div className="flex justify-between"><span>Cached input tokens (recent)</span><b>{n(cachedTokens)}</b></div><div className="mt-2 flex justify-between"><span>Recent ledger cost</span><b>{money(recentCosts)}</b></div></div></div></section>
    <section className="rounded-lg border border-gray-200 bg-white"><div className="flex items-center justify-between border-b border-gray-200 px-5 py-4"><div><h2 className="font-semibold">Platform activity</h2><p className="text-xs text-gray-500">Audit events are the source of truth for what changed.</p></div><Link href="/app/superuser/audit" className="text-xs font-semibold text-blue-700">Open audit</Link></div><div className="divide-y divide-gray-100">{(auditRows.data || []).slice(0,8).map((r:any)=><div key={r.id} className="grid grid-cols-[150px_1fr_auto] gap-4 px-5 py-3 text-sm"><span className="text-xs text-gray-500">{dt(r.occurred_at)}</span><span><b>{r.action || r.event_type || 'Event'}</b>{r.entity_type ? ` · ${r.entity_type}` : ''}</span><span className="text-xs text-gray-500">{r.event_type || '—'}</span></div>)}{!(auditRows.data || []).length && <div className="px-5 py-6 text-sm text-gray-500">No audit events recorded.</div>}</div></section>
    <section className="rounded-lg border border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-900"><b>Support tickets:</b> the current production schema does not contain a support-ticket table, so this control plane does not invent a ticket count. A real ticket queue needs to be persisted before it can appear here.</section>
  </div>;
}
