import { getServiceClient } from '../../../../lib/auth';
import { formatCurrency, formatDate, formatNumber } from '../../../../lib/admin-data';

export default async function AiRunsPage() {
  const supabase = getServiceClient();
  const { data, error } = await supabase.from('ai_runs').select('id, account_id, model, input_tokens, output_tokens, total_cost, status, created_at').order('created_at', { ascending: false }).limit(250);
  const { data: accounts } = await supabase.from('accounts').select('id, name');
  const accountNames = new Map((accounts || []).map((account) => [account.id, account.name]));
  return <div className="space-y-6"><div><p className="text-sm font-medium text-blue-700">AI operations</p><h1 className="mt-1 text-3xl font-semibold text-gray-900">AI runs</h1><p className="mt-2 text-sm text-gray-600">Most recent 250 live records from <code>ai_runs</code>.</p></div>{error ? <p className="rounded border border-red-200 bg-red-50 p-4 text-sm text-red-700">Unable to load AI runs: {error.message}</p> : <div className="overflow-x-auto rounded-lg border border-gray-200 bg-white"><table className="min-w-full divide-y divide-gray-200 text-sm"><thead className="bg-gray-50 text-left text-xs uppercase tracking-wide text-gray-500"><tr><th className="px-5 py-3">Run</th><th className="px-5 py-3">Tenant</th><th className="px-5 py-3">Model</th><th className="px-5 py-3">Tokens</th><th className="px-5 py-3">Cost</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Started</th></tr></thead><tbody className="divide-y divide-gray-100">{(data || []).map((row) => <tr key={row.id}><td className="px-5 py-4 font-mono text-xs text-gray-600">{row.id}</td><td className="px-5 py-4 text-gray-600">{row.account_id ? accountNames.get(row.account_id) || row.account_id : '—'}</td><td className="px-5 py-4 text-gray-600">{row.model || '—'}</td><td className="px-5 py-4 text-gray-600">{formatNumber(Number(row.input_tokens || 0) + Number(row.output_tokens || 0))}</td><td className="px-5 py-4 text-gray-600">{formatCurrency(Number(row.total_cost || 0))}</td><td className="px-5 py-4 text-gray-600">{row.status || '—'}</td><td className="px-5 py-4 text-gray-600">{formatDate(row.created_at)}</td></tr>)}{!data?.length && <tr><td colSpan={7} className="px-5 py-10 text-center text-gray-500">No AI run records available.</td></tr>}</tbody></table></div>}</div>;
}
